name: Build Lib

env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  DOTNET_NOLOGO: true
  DOTNET_VERSION: 8.0.x
  PackageDir: ${{ github.workspace }}/nuget

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET 6.0.402
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 6.0.402
      - name: Install Cake Tool
        run: dotnet tool install -g cake.tool --version 0.38.5
      - name: Install cocoapods
        run: gem install cocoapods
      - name: Restore workloads
        run: dotnet workload restore
        working-directory: lib/GoogleApisForiOSComponents
      - name: Build iOS bindings
        run: dotnet cake
        working-directory: lib/GoogleApisForiOSComponents